version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: video_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - db_vs_data:/var/lib/postgresql/data

volumes:
  db_vs_data:
