services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: video_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - db_vs_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: video-redis
    command: >
      redis-server
      --save 900 1
      --save 300 10
      --appendonly yes
      ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}}
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redisdata:/data

volumes:
  db_vs_data:
  redisdata:
