spring:
  config:
    activate:
      on-profile: schema-print

  main:
    web-application-type: none
    lazy-initialization: true

  graphql:
    schema:
      printer:
        enabled: true
        # Gradle task overrides this with an absolute path, keep fallback:
        schema-location: ${app.graphql.schema.output}
  cache:
    type: none
  # Prevent infra autoconfig during schema printing
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.reactive.ReactiveOAuth2ResourceServerAutoConfiguration

app:
  graphql:
    schema:
      output: build/generated/graphql/schema.graphqls